# Etapa 1: Construir la aplicación Angular
FROM node:18 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y git
RUN npm cache clean --force

# Clonar el repositorio y construir la aplicación
RUN git clone https://github.com/Samurbinx/Frontend.git . && \
   npm install && \
   npm install -g @angular/cli && \
   ng build

ARG HOST_IP
RUN echo "HOST_IP is $HOST_IP"   
RUN find . -type f -exec sed -i "s/192.168.1.135/$HOST_IP/g" {} +

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:alpine

# Copiar el archivo de configuración de Nginx
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los archivos construidos a Nginx
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
