# Etapa 1: Construir la aplicación Angular
FROM node:18 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y git

# Clonar el repositorio y construir la aplicación
RUN git clone https://github.com/Samurbinx/Frontend.git . && \
   npm install && \
   npm install -g @angular/cli && \
   ng build

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:alpine

# Copiar el archivo de configuración de Nginx
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los archivos construidos a Nginx
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html

# Copiar el script desde la etapa builder
COPY --from=builder /usr/local/bin/replaceIP.sh /usr/local/bin/replaceIP.sh

# Hacer ejecutable el script
RUN chmod +x /usr/local/bin/replaceIP.sh

EXPOSE 80

CMD ["/bin/sh", "-c", "/usr/local/bin/replaceIP.sh && nginx -g 'daemon off;'"]
