version: '3.8'

services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200" 
    volumes:
      - ./frontend:/app # Sincronizamos el código del frontend con el contenedor
    environment:
      - NODE_ENV=production
    command: npm start 

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080" 
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://user:password@db:3306/dbname 
    volumes:
      - ./backend:/var/www/html 
    depends_on:
      - db 

  # Base de datos: Contenedor MySQL
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   
      MYSQL_DATABASE: portfolio           
      MYSQL_USER: root                    
      MYSQL_PASSWORD: rootpassword        
    volumes:
      - db_data:/var/lib/mysql             # Persistencia de datos de la base de datos
    ports:
      - "3306:3306"                        

# Volúmenes para persistencia de datos de MySQL
volumes:
  db_data:
